name: Auto-Build
on:
  push:
    branches: [ master ]

env:
    TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
    TMDB_API_ACCOUNT_ID: ${{ secrets.TMDB_API_ACCOUNT_ID }}
    TMDB_API_SESSION_ID: ${{ secrets.TMDB_API_SESSION_ID }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            6
            7
            8
          
      - name: Test
        run: dotnet test -c release
